/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataDisplay: typeof import('./components/DataDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkspaceManager: typeof import('./components/WorkspaceManager.vue')['default']
    WorkspaceTab: typeof import('./components/WorkspaceTab.vue')['default']
  }
}
